name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_PASSWORD }}
    - name: Set up QEMU dependency
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build controller image
      if: steps.changed-files-plantcontroller.outputs.any_changed == 'true'
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.context }}
        tags: ${{ env.image_name_controller }}
        platforms: linux/arm64,linux/amd64
        push: true
      env:
        context: ./controller
    - name: Build the Docker image
      run: |
        currImage="rockclimber81/cni-plugins:dev"
        docker buildx build --platform linux/amd64,linux/arm64 --build-arg version=${{ vars.version }} -t $currImage --push .
        docker logout